FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.12.1-cpu

RUN pip3 install tensorflow keras flask numpy

ADD ./inference.py /opt/inference.py


ENV FLASK_APP=/opt/inference.py
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]
