FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.12.0-cpu-py310

ADD ./requirements.txt /opt/ml/code/requirements.txt
RUN pip install -r /opt/ml/code/requirements.txt

ADD ./training.py /opt/ml/code/training.py

ENV SAGEMAKER_PROGRAM training.py

