FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.12.0-cpu-py310

ADD ./requirements.txt /opt/ml/code/requirements.txt
RUN pip install -r /opt/ml/code/requirements.txt

ADD ./main.py /opt/ml/code/main.py

ADD ./abalone.py /opt/ml/code/abalone.py

ENV SAGEMAKER_PROGRAM main.py

